name: hootsuite-ml-env
channels:
  - snowflake
dependencies:
  - python=3.11
  - snowflake-snowpark-python=1.14.0
  - snowflake-ml-python=1.5.0
  - pandas=2.1.4
  - scikit-learn=1.3.0
  - numpy=1.26.4
  - joblib
  - streamlit=1.32.0
