name: hootsuite-ml-env
channels:
  - snowflake
dependencies:
  - python=3.9
  - snowflake-snowpark-python=1.12.0
  - snowflake-ml-python=1.2.1
  - scikit-learn=1.3.0
  - pandas=2.1.4
  - numpy=1.26.3
  - streamlit=1.31.0
